### ISSUE TITLE
doc: readme still says under bsd 3 clause 

### ISSUE THREAD

**Issue by sammy-ette** [lukewhrit/spacebin#130]
It seems that since Spacebin was moved to GPL 3, you guys forgot to change the license on the readme to indicate that it is GPL. Currently, it still says that the project is under BSD 3-clause.

This is a pretty easy problem to fix, but i'll leave it to you as to how you want it to say "this project is GPL 3"

**Comment by lukewhrit** [comment]
Yep, you're right. I'll get around to fixing the README whenever possible.

**Comment by lukewhrit** [comment]
Closed by [`36d67a8`](https://github.com/spacebin-org/spirit/commit/36d67a8fa01c1d34106cf7c52a21a9b73ae5518b).
