### ISSUE TITLE
bug: sanitize and validate JSON before using it in routes

### ISSUE THREAD

**Issue by jackiedorland** [lukewhrit/spacebin#40]
**__REMEMBER__: Issues related to the cli client or frontend will not be tolerated in this repo. This is for server/backend issues only. Check the box below if you understand:**
- [x] I understand.

**Describe the bug**
A clear and concise description of what the bug is.. In other words, what happened?

Validation isn't completed on routes.

**Expected behavior**
A clear and concise description of what you expected to happen. (what didn't it do?)

Inputs should be validated to not contain escape characters, code, among other XSS vulnerabilities.

**Comment by lukewhrit** [comment]
This will eventually be implemented using [Joi](https://npmjs.com/package/@hapi/joi) and just basic escaping of fields.

There are also currently headers in place to deter XSS attacks thanks to [koa-helmet](https://npmjs.com/package/koa-helmet).

**Comment by lukewhrit** [comment]
XSS is purely client-side therefore spacebin will not do anything more than set headers to deter it.

**Comment by jackiedorland** [comment]
CSP 👏 

I may hate CSP's guts when it comes to userscripts, but setting a CSP header would help deter outside scripts (and perhaps people running scripts on the page, too!)

**Comment by lukewhrit** [comment]
> CSP 
> 
> I may hate CSP's guts when it comes to userscripts, but setting a CSP header would help deter outside scripts (and perhaps people running scripts on the page, too!)

`koa-helmet` can handle `contentSecurityPolicy` for us, we just need to enable it.

**Comment by jackiedorland** [comment]
sounds good to me: this may cause a few issues with selfhosted instances then. We should make it clear it allows scripts/css from a specific folder, perhaps a folder named `media`?

**Comment by lukewhrit** [comment]
> sounds good to me: this may cause a few issues with selfhosted instances then. We should make it clear it allows scripts/css from a specific folder, perhaps a folder named `media`?

I think `assets` would be a better name.

Also, see: [`bfa96f4`](https://github.com/spacebin-for-astronauts/spacebin/commit/bfa96f420e3f9e8fc01be0ebd31c37f4a7cca1e4)

**Comment by jackiedorland** [comment]
The only browser I could see CSP becoming a problem on would be Safari, but [Cascadea](https://cascadea.app) pretty much solves the injecting CSS issue.

Also, sounds good. I'll be "safari tester", I guess.

**Comment by lukewhrit** [comment]
> sounds good to me: this may cause a few issues with selfhosted instances then. We should make it clear it allows scripts/css from a specific folder, perhaps a folder named `media`?

Also, I think we'll want a config option for enabling/disabling CSP.

**Comment by jackiedorland** [comment]
Sure; CSP can be the bane of developer existence sometimes.

**Comment by lukewhrit** [comment]
> This will eventually be implemented using [Joi](https://npmjs.com/package/@hapi/joi) and just basic escaping of fields.
> 
> There are also currently headers in place to deter XSS attacks thanks to [koa-helmet](https://npmjs.com/package/koa-helmet).

I said here that we're going to use [Joi](https://npmjs.com/package/@hapi/joi), I'm now unsure. Joi is by far the most popular but it doesn't seem to have good support for Koa. I'm researching [yup](https://github.com/jquense/yup) as an alternative that will most likely support Koa.

**Comment by lukewhrit** [comment]
Alright. So, we're going to move to [`@koa/joi-router`](https://github.com/koajs/joi-router), this allows us to implement validation relatively easy using Joi. Implementing this requires a small refactoring in how we do routes but I think it will be easy enough and definitely worth it.

**Comment by lukewhrit** [comment]
CSP is also currently a bit broken, I need to setup directives. I'll get to work on fixing it soon.

**Comment by lukewhrit** [comment]
In progress.

**Comment by lukewhrit** [comment]
Closed due to [`de1464f`](https://github.com/spacebin-org/spacebin/commit/de1464f2c4947364f59964b8d75828ad2f19b895).
