### ISSUE TITLE
docs: Write endpoint documentation

### ISSUE THREAD

**Issue by jackiedorland** [lukewhrit/spacebin#41]
Under `wiki`, perhaps?

**Comment by lukewhrit** [comment]
Should've read the wiki smh https://github.com/spacebin-for-astronauts/spacebin/wiki/API-Endpoints

**Comment by jackiedorland** [comment]
It's quite unfinished?

**Comment by lukewhrit** [comment]
> It's quite unfinished?

Well yeah, but so are the endpoints themselves.

**Comment by jackiedorland** [comment]
> > It's quite unfinished?
> 
> Well yeah, but so are the endpoints themselves.

This is my point :suspect:

**Comment by jackiedorland** [comment]
This should definitely be an Alpha issue, though :feelsgood:

**Comment by lukewhrit** [comment]
Done.
