### ISSUE TITLE
bug: Starting server with `yarn start` errors with RepositoryNotFoundError

### ISSUE THREAD

**Issue by lukewhrit** [lukewhrit/spacebin#49]
**__REMEMBER__: Issues related to the cli client or frontend will not be tolerated in this repo. This is for server/backend issues only. Check the box below if you understand:**
- [X] I understand.

**Describe the bug**

Starting server with `yarn start` errors with `RepositoryNotFoundError: No repository for "undefined" was found. Looks like this entity is not registered in current "default" connection?`.

Stack trace:
```
▶ yarn start
yarn run v1.22.4
$ yarn build && node dist/server.js
$ ./node_modules/.bin/swc src/ -s -d dist/
Successfully compiled 8 files with swc.
Spacebin started on 0.0.0.0:7777
(node:55636) UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "undefined" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/home/luke/code/git/spacebin/spacebin/node_modules/typeorm/error/RepositoryNotFoundError.js:11:28)
    at EntityManager.getRepository (/home/luke/code/git/spacebin/spacebin/node_modules/typeorm/entity-manager/EntityManager.js:670:19)
    at Connection.getRepository (/home/luke/code/git/spacebin/spacebin/node_modules/typeorm/connection/Connection.js:344:29)
    at /home/luke/code/git/spacebin/spacebin/dist/routes/document.route.js:1:1304
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/luke/code/git/spacebin/spacebin/dist/routes/document.route.js:1:530)
    at _next (/home/luke/code/git/spacebin/spacebin/dist/routes/document.route.js:1:845)
(node:55636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:55636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

1. `yarn start`
2. See error.

**Expected behavior**

The server should've ran with no issues.

**Screenshots**

N/A

**Additional context**

* This issue does not happen when running with `ts-node` (`yarn watch`). I'm unsure as to why.
* I'm using node version 12.

**Comment by heyitspuggo** [comment]
Hold on, let me test this out

**Comment by heyitspuggo** [comment]
![2020-06-04T22:48:58Z](https://user-images.githubusercontent.com/16177268/83817975-21c2b300-a694-11ea-8c4d-b633b224f9d1.png)
Can't repro; try reinstalling node or committing and re-cloning.

**Comment by jackiedorland** [comment]
![Screen Shot 2020-06-04 at 6 55 15 PM](https://user-images.githubusercontent.com/16177268/83818278-ee345880-a694-11ea-92cf-be3a05f22876.png)
I take it back; I can repro..

**Comment by lukewhrit** [comment]
I think I have a quick and dirty patch I can make. Just making (and possibly keeping open) a connection when the server starts will probably work.

Update: This did not work. After some investigating it may be an issue with how we load our entities.

**Comment by jackiedorland** [comment]
I'll be assigning Urgent to this issue; Please link a PR you think would fix it when it's ready.

**Comment by lukewhrit** [comment]
> I'll be assigning Urgent to this issue; Please link a PR you think would fix it when it's ready.

Working on it.

**Comment by lukewhrit** [comment]
Our built document entity has no content. 

![image](https://user-images.githubusercontent.com/38197656/83818897-72d3a680-a696-11ea-9c2c-446e1333437b.png)

So, this must be an issue with swc's building decorators.

**Comment by jackiedorland** [comment]
Sounds good; What's the TS code look like? Are you sure you handled the asnyc/await properly?

**Comment by lukewhrit** [comment]
> Sounds good; What's the TS code look like? Are you sure you handled the asnyc/await properly?

```ts
import { Entity, Column, PrimaryColumn } from 'typeorm'
import config from '../config'

@Entity()
export class Document {
  @PrimaryColumn({
    // Enforce key length
    length: config.options.keyLength
  })
  id: string

  @Column()
  content: string
}
```

It has the class decorator but doesn't seem to have any field decorators

**Comment by lukewhrit** [comment]
I think that in order to fix this we need to start using a different TS compiler.

I suggest rollup with the rollup typescript plugin.

**Comment by jackiedorland** [comment]
Rest in peace `swc` 🙏 ⚰️ :suspect:

What else is there? I guess rollup could be fine, too.
Make an issue about it in the `swc` GitHub; I hope that's fixed soon enough.

**Comment by lukewhrit** [comment]
> Rest in peace `swc`   :suspect:
> 
> What else is there? I guess rollup could be fine, too.
Actually, we could possibly use [esbuild](https://github.com/evanw/esbuild).

Update: After some research, esbuild is not a viable option. It has no support for decorators. [See more here](https://github.com/evanw/esbuild/issues/104).

> Make an issue about it in the `swc` GitHub; I hope that's fixed soon enough.

I'll make an issue when this is confirmed to be an issue with `swc` and not something else.

Update: This was confirmed to be an issue with `swc`, however someone else already created the issue.

**Comment by lukewhrit** [comment]
Webpack, Rollup, and standard TSC are probably the best options.

TSC may be the best out of those. We haven't needed a more advanced build tool chain yet which is the main purpose of tools like Rollup.

**Comment by jackiedorland** [comment]
Sounds good to me; `tsc` usually the most stable imo

**Comment by lukewhrit** [comment]
> Sounds good to me; `tsc` usually the most stable imo

Alright. I'll put up a branch and move to `tsc`.

**Comment by lukewhrit** [comment]
> > Sounds good to me; `tsc` usually the most stable imo
> 
> Alright. I'll put up a branch and move to `tsc`.

Done. See the [`lukewhrit-tsc`](https://github.com/spacebin-for-astronauts/spacebin/tree/lukewhrit-tsc) branch.
