### ISSUE TITLE
docs: Start keeping a changelog

### ISSUE THREAD

**Issue by jackiedorland** [lukewhrit/spacebin#56]
https://keepachangelog.com/en/1.0.0/

**Comment by lukewhrit** [comment]
Pushed a `CHANGELOG.md` file to [`develop`](https://github.com/spacebin-for-astronauts/spacebin/tree/develop) in [`198c091`](https://github.com/spacebin-for-astronauts/spacebin/commit/198c091a21227d4786217d04be7041d4e88a9dbe). This will just serve as a placeholder, and we'll start updating it when 0.1.0 comes around.

**Comment by lukewhrit** [comment]
I think we can close this.
