### ISSUE TITLE
feat: Idempotency token confirmation to prevent duplicate uploads

### ISSUE THREAD

**Issue by jackiedorland** [lukewhrit/spacebin#58]
**__REMEMBER__: Issues related to the [CLI client](https://github.com/spacebin-for-astronauts/cli) or [frontend](https://github.com/spacebin-for-astronauts/frontend) will not be tolerated in this repository. This is for server/backend issues only. Check the box below if you understand:**    
- [x] I understand.

**Describe the solution you'd like**

When the Server receives a request, it requires an extra parameter, being `idemp_token`. If that exact query has happened more than once, within 10 minutes from eachother, discard query and return same content/url/id every time.

**Additional context**

This would prevent spam and help out (if frustrated with client/upload) it would prevent the need for a new DB entry each time.

**Comment by lukewhrit** [comment]
I'll need to research Idempotency before implementing this but it sounds like it would be a good addition.
