### ISSUE TITLE
bug: automatically delete documents after the `maxAge` passes.

### ISSUE THREAD

**Issue by lukewhrit** [lukewhrit/spacebin#70]

**Comment by jackiedorland** [comment]
Hmm. I don't love the idea of `maxAge`, considering that some people link to pastes indefinitely. Perhaps this could be a user-set variable and not an enforced standard across the platform? A better way of doing this could be a 16-bit maximum character limit, i.e. `0-65355`

**Comment by lukewhrit** [comment]
> Hmm. I don't love the idea of `maxAge`, considering that some people link to pastes indefinitely. Perhaps this could be a user-set variable and not an enforced standard across the platform? A better way of doing this could be a 16-bit maximum character limit, i.e. `0-65355`

This is just a feature carried over from hastebin, I suppose we could make it user set. Having it user-set sounds like a good spot for explotation.

Also, there already is a configurable maximum character limit (default: 400,000 chars).

**Comment by jackiedorland** [comment]
Well, what's the default max age for pastes in Haste? I'd say 10 years is a good goal if we do implement a `maxAge` config

**Comment by lukewhrit** [comment]
> Well, what's the default max age for pastes in Haste? I'd say 10 years is a good goal if we do implement a `maxAge` config

By default it's disabled. I think the public haste instances deletes documents after 30 days.

**Comment by jackiedorland** [comment]
Hmm. For safety's sake, I'd say a default of 90 days would be good. Private instances will also have to be a thing, similar to [whats-this/api](https://github.com/whats-this/api)

**Comment by lukewhrit** [comment]
> Hmm. For safety's sake, I'd say a default of 90 days would be good. Private instances will also have to be a thing, similar to [whats-this/api](https://github.com/whats-this/api)

Default of 90 days sounds good but private instances sounds more like a v1.0.0 because of user authentication

**Comment by lukewhrit** [comment]
I don't think this is possible. Hastebin handles all document expiration in the database, and TypeORM does not give us the ability to.

---

@heyitspuggo suggested running a cron job daily to see if a document was expired, but I believe this could become a resource & time intensive for massive instances.

**Comment by lukewhrit** [comment]
@GreatGodApollo proposed a new solution, "put a `documentExpiration` field in the database, and check if it's expired when it's requested". I think this solution could work very well, although it would make requests take slightly longer.

**Comment by jackiedorland** [comment]
That doesn't solve the core issue; the issue is that too many pastes might become storage intensive for the instance, and removing a paste when it's requested wouldn't work for extremely old pastes that are used one time and never again.

**Comment by lukewhrit** [comment]
> That doesn't solve the core issue; the issue is that too many pastes might become storage intensive for the instance, and removing a paste when it's requested wouldn't work for extremely old pastes that are used one time and never again.

I don't know what else we can do then. A cron-job could work but it could end up taking too long or become too memory-intensive.

**Comment by jackiedorland** [comment]
Parallelism exists, and I doubt anyone would be running this without 2 or more cores.

Nevermind. We're using node ;)

**Comment by lukewhrit** [comment]
I think we should target fixing this in `1.0.0`, since I currently can't think of a solution that wouldn't have any of those issues.

**Comment by lukewhrit** [comment]
A fix for this is being implemented in the [`curiosity`](spacebin-org/curiosity) repository. Still WIP.

**Comment by lukewhrit** [comment]
Closed by [`b05a75`](https://github.com/spacebin-org/spirit/commit/b05a7586aab8b7e021f144bca238e0da3a5ab3f6#diff-4a533304db224b81907074e8ac880987).
