### ISSUE TITLE
bug: POST to /api/v1/document returns content when it should return hash

### ISSUE THREAD

**Issue by jackiedorland** [lukewhrit/spacebin#74]
**__REMEMBER__: Issues related to the [CLI client](https://github.com/spacebin-for-astronauts/cli) or [frontend](https://github.com/spacebin-for-astronauts/frontend) will not be tolerated in this repository. This is for server/backend issues only. Check the box below if you understand:**
- [x] I understand.

**Describe the bug**
A clear and concise description of what the bug is.. In other words, what happened?
POSTing to `/api/v1/document` returns `content`, and `id`. 

This isn't sustainable, nor a good idea for a few reasons:
- POST request bodies shouldn't be giant (in case of large files) 
- POST request bodies may flood buffers that are holding the content of the POST request, potentially causing slowdown
- Hashes should be in SHA-256 format to reduce size and keep POST requests standardized and clean.

**Expected behavior**
A clear and concise description of what you expected to happen. (what didn't it do?)

Upon POST, the server should return something like this:
```
{ 
    "id":"<id of document>",
    "hash":"<SHA-256 hash of document contents>"
}
```
**Additional context**

I hope I'll never have to debug a four-hundred thousand character paste, but if I do, this will definitely help alot with the amount of data returned each POST.

**Comment by lukewhrit** [comment]
I argued about this a lot but whatever, I'll implement it. It's very easy and I guess added complexity in routes isn't too bad.

**Comment by jackiedorland** [comment]
I can always reassign this to myself and work on it.

**Comment by lukewhrit** [comment]
Fixed in [`44221e`](https://github.com/spacebin-org/spacebin/commit/44221e75d5908764fd55e2ba8c0db4ee08b84e65)

**Comment by jackiedorland** [comment]
👍
